apiVersion: v1
kind: Pod
metadata:
    name: web-letter
    labels:
        app: web-letter
spec:
    containers:
        - name: web-letter
          image: "ghcr.io/hiromuraki/web-letter:latest"
          env:
              - name: LETTER_FILE
                value: "/data/letter"
              - name: FILES_DIR
                value: "/data/files/"
          ports:
              - containerPort: 8000
                hostPort: 8032
          volumeMounts:
              - name: data-volume
                mountPath: /data
    volumes:
        - name: data-volume
          hostPath:
              path: /path/to/data
              type: DirectoryOrCreate
