name: Build Go Project

on:
    push:
        branches:
            - main
        paths:
            - ".github/workflows/build-binary.yml"
            - "core/**"
            - "static/**"
            - "main.go"
            - "go.mod"
            - "go.sum"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.26" #
                  cache: true

            - name: Run Build via Makefile
              run: make all

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: multi-arch-binaries
                  path: dist/*
                  retention-days: 5
